import { Inter } from "next/font/google";
import "./globals.css";
import MenuNavbar from "@/components/menubar/Menubar";
import BreadCrumb from "@/components/breadcrumbs/BreadCrumb";
import { Theme } from "@radix-ui/themes";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/icons/icon-192x192.png" />
        <meta name="theme-color" content="#000000" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={inter.className}>
        <Theme>
          <MenuNavbar />
          <BreadCrumb />
          {children}
        </Theme>
      </body>
    </html>
  );
}
